// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/PrimitiveSerializer.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
using System.Buffers;
namespace ExcelSerializerLib.Serializers
{
    public sealed class BooleanExcelSerializer : IExcelSerializer<Boolean>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Boolean value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Boolean value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class ByteExcelSerializer : IExcelSerializer<Byte>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Byte value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Byte value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class SByteExcelSerializer : IExcelSerializer<SByte>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, SByte value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, SByte value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class DecimalExcelSerializer : IExcelSerializer<Decimal>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Decimal value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Decimal value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class DoubleExcelSerializer : IExcelSerializer<Double>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Double value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Double value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class SingleExcelSerializer : IExcelSerializer<Single>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Single value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Single value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class Int32ExcelSerializer : IExcelSerializer<Int32>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int32 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int32 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class UInt32ExcelSerializer : IExcelSerializer<UInt32>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt32 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt32 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class Int64ExcelSerializer : IExcelSerializer<Int64>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int64 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int64 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class UInt64ExcelSerializer : IExcelSerializer<UInt64>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt64 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt64 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class Int16ExcelSerializer : IExcelSerializer<Int16>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int16 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, Int16 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

    public sealed class UInt16ExcelSerializer : IExcelSerializer<UInt16>
    {        
		public void WriteTitle(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt16 value, ExcelSerializerOptions options, string name = "value")
            => formatter.Write(name, writer);

        public void Serialize(ref ExcelFormatter formatter, IBufferWriter<byte> writer, UInt16 value, ExcelSerializerOptions options)
            => formatter.WritePrimitive(value, writer);
    }

}

namespace ExcelSerializerLib.Providers
{
    public sealed partial class PrimitiveExcelSerializerProvider
    {
        internal partial void InitPrimitives()
        {
            serializers[typeof(System.Boolean)] = new Serializers.BooleanExcelSerializer();
            serializers[typeof(System.Byte)] = new Serializers.ByteExcelSerializer();
            serializers[typeof(System.SByte)] = new Serializers.SByteExcelSerializer();
            serializers[typeof(System.Decimal)] = new Serializers.DecimalExcelSerializer();
            serializers[typeof(System.Double)] = new Serializers.DoubleExcelSerializer();
            serializers[typeof(System.Single)] = new Serializers.SingleExcelSerializer();
            serializers[typeof(System.Int32)] = new Serializers.Int32ExcelSerializer();
            serializers[typeof(System.UInt32)] = new Serializers.UInt32ExcelSerializer();
            serializers[typeof(System.Int64)] = new Serializers.Int64ExcelSerializer();
            serializers[typeof(System.UInt64)] = new Serializers.UInt64ExcelSerializer();
            serializers[typeof(System.Int16)] = new Serializers.Int16ExcelSerializer();
            serializers[typeof(System.UInt16)] = new Serializers.UInt16ExcelSerializer();
        }
    }
}